services:
  app:
    build: .
    restart: always
    ports:
      - 3000:3000
    environment:
      SECRET_KEY: ${SECRET_KEY}
      PLATFORM_BASE_URL: ${PLATFORM_BASE_URL}
      MONGODB_USERNAME: ${MONGODB_USERNAME}
      MONGODB_PASSWORD: ${MONGODB_PASSWORD}
      MONGODB_HOST: mongo
  mongo:
    image: mongo:7.0
    command: [--auth]
    restart: always
    volumes:
      - ./data/mongo:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
